### ISSUE TITLE
panic during panic

### ISSUE THREAD

**Issue by mcuadros** [olebedev/go-duktape#17]
After spent more than 3 hours, thinking that I was making something wrong, looks like is not my fault.

If you run this piece of code you will fall on a "panic during panic". Any clue what is happening? I tried with other return values. If return is `-1` an error is returned, so the problem is not related with throwing errors

```go
func TestPushGlobalGoFunction_Error(t *testing.T) {
	ctx := Default()
	ctx.PushGlobalGoFunction("test", func(c *Context) int {
		ctx.Error(105, "foo")
		return 0
	})

	expect(t, len(ctx.fn), 1)
	ctx.PevalString("test()")
	ctx.DestroyHeap()
}
```

```
panic during panic

runtime stack:
runtime.startpanic_m()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.c:110 +0x108
runtime.onM(0x420ae38)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:273 +0x9a
runtime.startpanic()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:469 +0x14
runtime.throw(0x4292c1c)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:489 +0x35
runtime.newstack()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/stack.c:713 +0x19a
runtime.morestack()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:324 +0x7e

goroutine 14 [syscall, locked to thread]:
runtime.cgocall_errno(0x4001340, 0xc20805bc30, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/cgocall.go:130 +0xf5 fp=0xc20805bc10 sp=0xc20805bbe8
github.com/olebedev/go-duktape._Cfunc__duk_error(0x44174e0, 0x69, 0x4422c60)
	github.com/olebedev/go-duktape/_test/_obj_test/_cgo_gotypes.go:146 +0x45 fp=0xc20805bc30 sp=0xc20805bc10
github.com/olebedev/go-duktape.(*Context).Error(0xc20800a680, 0x69, 0xc20805bd18, 0x1, 0x1)
	/Users/mcuadros/workspace/go/src/github.com/olebedev/go-duktape/api.go:337 +0x187 fp=0xc20805bcc8 sp=0xc20805bc30
github.com/olebedev/go-duktape.func·006(0xc20800a6a0, 0xc20803c6f0)
	/Users/mcuadros/workspace/go/src/github.com/olebedev/go-duktape/duktape_test.go:82 +0xf9 fp=0xc20805bd48 sp=0xc20805bcc8
github.com/olebedev/go-duktape.goFuncCall(0x44174e0, 0x0)
	/Users/mcuadros/workspace/go/src/github.com/olebedev/go-duktape/duktape.go:230 +0x1da fp=0xc20805bdc0 sp=0xc20805bd48
runtime.call16(0x7fff5fbfefb0, 0x7fff5fbff030, 0x10)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:401 +0x45 fp=0xc20805bdd8 sp=0xc20805bdc0
runtime.cgocallbackg1()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/cgocall.go:239 +0x12a fp=0xc20805be38 sp=0xc20805bdd8
runtime.throw(0x4296059)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:490 +0x6e fp=0xc20805be68 sp=0xc20805be38
runtime.exitsyscall(0x4001af0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:1899 +0x4f fp=0xc20805be88 sp=0xc20805be68
runtime.cgocall_errno(0x4001af0, 0xc20805bed0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/cgocall.go:132 +0x11a fp=0xc20805beb0 sp=0xc20805be88
github.com/olebedev/go-duktape._Cfunc__duk_peval_string(0x44174e0, 0x44220d0, 0x1)
	github.com/olebedev/go-duktape/_test/_obj_test/_cgo_gotypes.go:284 +0x43 fp=0xc20805bed0 sp=0xc20805beb0
github.com/olebedev/go-duktape.(*Context).PevalString(0xc20800a680, 0x41cb970, 0x6, 0x0, 0x0)
	/Users/mcuadros/workspace/go/src/github.com/olebedev/go-duktape/api.go:859 +0x83 fp=0xc20805bf10 sp=0xc20805bed0
github.com/olebedev/go-duktape.TestPushGlobalGoFunction_Trow(0xc208074510)
	/Users/mcuadros/workspace/go/src/github.com/olebedev/go-duktape/duktape_test.go:87 +0x195 fp=0xc20805bf78 sp=0xc20805bf10
testing.tRunner(0xc208074510, 0x4287158)
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:447 +0xbf fp=0xc20805bfd0 sp=0xc20805bf78
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20805bfd8 sp=0xc20805bfd0
created by testing.RunTests
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x420ab78, 0x4287080, 0xe, 0xe, 0x1)
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208050140, 0x429f3a0)
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:485 +0x6c
main.main()
	github.com/olebedev/go-duktape/_test/_testmain.go:78 +0x1d5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

![bluescreen-fail-double-fail](https://cloud.githubusercontent.com/assets/1573114/7802980/79913c2c-0343-11e5-9c2f-b3100eeaab0c.jpg)

**Comment by mcuadros** [comment]
https://github.com/ivan4th/go-duktape/commit/515abae56abe684c912ab279f93d2c5dc3926795#diff-76b38c23563ff2a850abc6310d0c2739R205

**Comment by mcuadros** [comment]
BTW github.com/matwachich/goduk with the core updated to 1.2.1 work perfect with errors :/

**Comment by olebedev** [comment]
Could you provide code example with github.com/matwachich/goduk which is works perfect with errors?

**Comment by mcuadros** [comment]
The tests: 
https://github.com/matwachich/goduk/blob/master/goduk_test.go#L9

:D

**Comment by olebedev** [comment]
I have tried to run test with `duk_error_raw` function, which used in [this test](https://github.com/matwachich/goduk/blob/master/goduk_test.go#L9). But I have got same error.

**Comment by mcuadros** [comment]
Here or there? :D

**Comment by olebedev** [comment]
Here of course

**Comment by mcuadros** [comment]
easter egg on my last PR:  https://github.com/olebedev/go-duktape/blob/master/api.go#L341

**Comment by olebedev** [comment]
Is it works well?

**Comment by mcuadros** [comment]
nope, it produces the same error. I made the refactor to try to find the bug but still is there. But at least we have a working code. So the problem is on our code :/

**Comment by olebedev** [comment]
@mcuadros btw, why don't you use [#duk_push_error_object](http://duktape.org/api.html#duk_push_error_object) and don't return negative int to pick an error as described here [#duk_push_c_function](http://duktape.org/api.html#duk_push_c_function)?

**Comment by olebedev** [comment]
Obviously, the problem is not on our code https://github.com/svaarala/duktape/issues/154.

**Comment by mcuadros** [comment]
Yep I know is referenced on my readme, but thanks anyways. I have a pending email with @svaarala. I will try to make a work around. With tip the error is slightly different, the problem is that the heap targered by the longjmp not longer exists.

**Comment by olebedev** [comment]
Sure, link is from your readme. I leave it here to clarify the topic for all. Please, reopen this issue again if you find any significant info.

**Comment by mcuadros** [comment]
Yep I am speak with @svaaral, to push a custom errors on C functions. And we will need to wrap functions throwing errors into a duk_safe_call. I will keep you updated.

**Comment by mcuadros** [comment]
PTAL
https://github.com/mcuadros/go-duktape/commit/3d1f89e8e7b4a35f2879dff7564d6c74563dfb88
