### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer (go 1.6)

### ISSUE THREAD

**Issue by mirrr** [olebedev/go-duktape#34]
I got panic when I tried to compile this example from README.md
```go
package main

import "fmt"
import "gopkg.in/olebedev/go-duktape.v2"

func main() {
	ctx := duktape.New()
	ctx.PushGlobalGoFunction("log", func(c *duktape.Context) int {
		fmt.Println(c.SafeToString(-1))
		return 0
	})
	ctx.EvalString(`log('Go lang Go!')`)
}
```
 
Golang version: **go1.6 linux/amd64**

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x57c900, 0xc82000a4b0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
gopkg.in/olebedev/go-duktape%2ev2._cgoCheckPointer0(0x54a8c0, 0xc82002c028, 0x0, 0x0, 0x0, 0x53b9a0)
	gopkg.in/olebedev/go-duktape.v2/_obj/_cgo_gotypes.go:113 +0x4d
gopkg.in/olebedev/go-duktape%2ev2.(*Context).PushPointer(0xc82002c028, 0xc82002c028)
	/p/Go/src/gopkg.in/olebedev/go-duktape.v2/api.go:1450 +0x9c
gopkg.in/olebedev/go-duktape%2ev2.(*Context).PushGoFunction(0xc82002c028, 0x5e7530, 0x3)
	/p/Go/src/gopkg.in/olebedev/go-duktape.v2/duktape.go:87 +0xf1
gopkg.in/olebedev/go-duktape%2ev2.(*Context).PushGlobalGoFunction(0xc82002c028, 0x5a9958, 0x3, 0x5e7530, 0x5d0780, 0x0, 0x0)
	/p/Go/src/gopkg.in/olebedev/go-duktape.v2/duktape.go:70 +0x1ca
main.main()
	/p/Go/src/test/duktape.go:11 +0x4b
```

**Comment by olebedev** [comment]
Thanks for the report. As Go 1.6 has changed cgo a bit the go-duktape should be updated too. I'll do it asap.

If you need to use go-duktape in production systems please use Go 1.5.3.
